services:

    ai-agents:
        container_name: ai-agents
        build: .
        mem_limit: 2G
        # privileged: true
        environment:
            - AI_API_URL=${AI_API_URL:?}
            - AI_API_KEY=${AI_API_KEY:?}
            - AI_CONTEXT_LENGTH=64000
            - AI_MODEL=${AI_MODEL:-default}
            - AI_CHEAP_MODEL=${AI_MODEL:-cheap}
            - AI_VISION_MODEL=${AI_VISION_MODEL:-vision}
            - AUTHORIZED_PUBLIC_KEYS=${SSH_PUBLIC_KEY}
            - BRAVE_API_KEY=${BRAVE_API_KEY}
            - DOCKER_HOST=unix:///media/user/.docker.sock
            - SIGNAL_ACCOUNT=
            - SIGNAL_ALLOWED_USERS=
            - SIGNAL_SERVER_URL=http://signal-cli:8080
            - USER_PASSWORD=adminadminU1!
        tmpfs:
            - /etc/X11/xorg.conf.d:size=1M
            - /tmp:exec
        volumes:
            - "./data-local:/media/user"
        ports:
            - "127.0.0.1:8022:22"
            - "127.0.0.1:8002:11002"
            - "127.0.0.1:8003:11003"
            - "127.0.0.1:8900:5900"
